version: "3"

services:
  seisan-back:
    container_name: seisan-back
    networks:
      default:
      seisan-network:
        aliases:
          - seisan-back-container
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - ./src:/work
    tty: true
    restart: always
    depends_on:
      - db

  db:
    container_name: postgres
    networks:
      default:
      seisan-network:
        aliases:
          - postgres-container
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    tty: true
    restart: always

  redis:
    container_name: redis
    networks:
      default:
      seisan-network:
        aliases:
          - redis-container
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"

networks:
  seisan-network:
    external: true
